### ISSUE TITLE
Implement a method corresponding to the `_all_docs` view

### ISSUE THREAD

**Issue by KMax** [mkeen/rxcouch#7]
It's useful to have `_all_docs` method, especially for debugging purposes or dealing with a small database without indexes.

I see that there is `CouchDB.documents.ids` property, but here I mean the `_all_docs?include_docs=true` call which returns not only ids, but also the documents.

**Comment by mkeen** [comment]
@KMax I'll definitely implement this at some point, but probably not until my upstream project requires more robust `views` support. Since `_all_docs` is just a `view`, I would imagine making the existing `design` implementation more robust first would be the way to go here. Then more query params than just `include_docs` could be supported. If you want to take a stab at this, I welcome it. But if not, I'll have something here eventually.

**Comment by mkeen** [comment]
@KMax implemented in `4.12.14` as `.all()`, which returns an observable with holding the result of the _all_docs GET request.
